In [23]:
#From SAV to LOVE

# HW 4

In [24]:
import numpy as np

## Часть 1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$



### Решение

Перепишем СЛАУ в виде дополненной матрицы

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Отнимем от второйстроки первую, умноженную на 2, а от третьей строки отнимем просто первую строку и получим:
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Получается что СЛАУ у нас переопределенная система, так как число уравнение меньше чем неизвестных.

Выразим $x_4 = 2t$, тогда 

$-2 x_3 + 6 t = 4 \,\,\ \to \,\,\, x_3 = 3t-2$

$-x_2 + 3t -2 + 10t = -2 \,\,\, \to \,\,\, x_2 = 13t$

$x_1 + 13t - 3t +2 - 4 t = 0\,\,\, \to \,\,\, x_1 = -6t - 2$

Решение:

$$ X = \begin{pmatrix}
-6t-2\\ 
13t\\
3t-2\\
2t
\end{pmatrix}$$




In [25]:
# chek

A = np.array([
              [1,1,-1,-2],[2,1,-1,1],[1,1,-3,1]
            ])
t = 1
X = np.array([
              [-6*t - 2],[13*t],[3*t - 2],
              [2*t]
            ])


A.dot(X)

array([[ 0],
       [-2],
       [ 4]])

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$




### Решение

__а)__

У нас число неизвестных равно количеству уравнений.
Запишем матрицу коэффициентов:

$$A = \begin{pmatrix}
3 & -1 & 1\\
2 & -5 & -3\\
1 & 1 & -1
\end{pmatrix}$$

Ее определитель  $det = 15+3+2-(-5) -(-9) -2 = 33 > 0$, следовательно СЛАУ совместна и имеет единственное решение

__б)__

У нас число неизвестных равно количеству уравнений, 
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3\\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$$

доумножим первую строку на 3, вторую на 6, а третью на 2:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
6 & -12 & 18 \\ 
6 & -12 & 18\\ 
6 & -12 & 18
\end{matrix}\right|
\begin{matrix}
3\\ 
-12\\
10
\end{matrix}
\end{pmatrix}$$

Видим что при одинаковых коэффициентах слева у нас получается разная правая часть, следовательно система несовместа


__в)__

Количество уравнений меньше количества неизвестных, кроме того вектора коэффициентов независимы ($\begin{pmatrix} 1\\ 3 \end{pmatrix},\begin{pmatrix} 2\\ 1 \end{pmatrix}, \begin{pmatrix} 5\\ -8 \end{pmatrix}$), следовательно система совместна и имеет бесконечное число решений

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$



### Решение

Здесь $rank A = rank\tilde{A} = n$, так как определитель $detA  = 1*5*3*2 = 30 >0$, 

следовательно, так как у нас 4 уравнения с 4 неизвестными, то система определена и имеет единственное решение.

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

### Решение

Определитель матрицы коэффициентов = 0, следовательно нам необходимо проверить соотношение коэффициентов $a,b,c$
Воспользуемся методом Гаусса:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix} $$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c - 7a
\end{matrix}
\end{pmatrix}$$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c - 7a - 2(b-4a)
\end{matrix}
\end{pmatrix} = \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c + a - 2b
\end{matrix}
\end{pmatrix}$$

Следовательно, для того чтобы система была несовместна, необходимо чтобы:

$$c+a-2b \neq  0$$


## Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$



### Решение 

__a)__

$x_{i}=\frac{detA_{i}}{detA}$

Найдем определитель матрицы коэффициентов:

$detA=\begin{vmatrix}
1 &  -2\\ 
3 & -4 
\end{vmatrix} = -4+6 = 2 > 0$, следовательно система совместна

$detA_1=\begin{vmatrix}
1 &  -2\\ 
7 & -4 
\end{vmatrix} = -4+14 = 10 $

$detA_2=\begin{vmatrix}
1 &  1\\ 
3 & 7 
\end{vmatrix} = 7 -3  = 4$

$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5$

$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$


__б)__

$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix}=
2+6+20-10+24+1 = 43\neq 0,$

следовательно, система совместна.

Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$:

$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix}= 10+3-40-5+120-2 = 86,$

$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix}= - 4 - 60 +5 +20+6-10 = -43
$

$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix}= 2+4+40-20+16+1 = 43 $

Тогда:

$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$

$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1,$

$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1.$


__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    


### Решение

__а)__$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$



Домножим первую строку на $2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. 

Домножим первую строку на $3$ и вычтем ее из третьего уравнения. При этом запишем в матрицу $L$ на место элемента $l_{31}$ значение $3$. 

Тогда:

$$U` = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix},$$

а матрица $L$ —

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}.$$

Домножим вторую строку на $4$ и вычтем ее из третьего уравнения. При этом запишем в матрицу $L$ на место элемента $l_{32}$ значение $4$.

Тогда:

$$U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix},$$

а матрица $L$ —

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}.$$


In [26]:
# chek
matrL = np.array([
              [1,0,0],
              [2,1,0],
              [3,4,1]
            ])
matrU = np.array([
              [1,2,4],
              [0,5,4],
              [0,0,2]
            ])
matrL.dot(matrU)

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

__б)__$$
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$



Домножим первую строку на $2$ и вычтем ее из второго уравнения. $l_{21} = 2$. 

Домножим первую строку на $3$ и вычтем ее из второго уравнения. $l_{31} = 3$. 

Домножим первую строку на $4$ и вычтем ее из второго уравнения. $l_{41} = 4$. 

Тогда:

$$U` = \begin{pmatrix}
1 & 1& 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
0 & 18 & 45 &  17
\end{pmatrix},$$

а матрица $L$ —

$$L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & l_{32} & 1&0\\
4 & l_{42} & l_{43} & 1
\end{pmatrix}.$$

Далее аналогично:

$l_{32} = 5$,

$l_{42} = 6$,

Тогда:

$$U` = \begin{pmatrix}
1 & 1& 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 21 & 11
\end{pmatrix},$$

а матрица $L$ —

$$L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1&0\\
4 & 6 & l_{43} & 1
\end{pmatrix}.$$

Далее:

$l_{43} = 7$,

Тогда:

$$U = \begin{pmatrix}
1 & 1& 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 0 &  4
\end{pmatrix},$$

а матрица $L$ —

$$L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1&0\\
4 & 6 & 7 & 1
\end{pmatrix}.$$

    

In [27]:
# chek
matrL2 = np.array([
              [1,0,0,0],
              [2,1,0,0],
              [3,5,1,0],
              [4,6,7,1]
            ])
matrU2 = np.array([
              [1,1,2,4],
              [0,3,4,1],
              [0,0,3,1],
              [0,0,0,4]
            ])
matrL2.dot(matrU2)

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$



# Решение

$$ A = \begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$$

разложим матрицу на LU

Тогда:

$$U = \begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix},$$

а матрица $L$ —

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}.$$


$L\cdot Y = b$

$ \begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}\cdot \begin{pmatrix}
y_1 \\ 
y_2 \\ 
y_3
\end{pmatrix} =  \begin{pmatrix}
1 \\ 
-6 \\ 
-5
\end{pmatrix}$



$$\begin{cases}
y_{1} =1 \\
\frac{11}{2}y_1+y_{2}=-6 \\
\frac{9}{2}y_{1}+\frac{7}{3}y_{2}+y_{3}=-5
\end{cases}$$

$y_1 = 1$

$y_2 = -6 - \frac{11}{2} = - \frac{23}{2}$

$y_3 = -5 - \frac{9}{2} - \frac{7}{3}\cdot(-\frac{23}{2}) = \frac{52}{3}$

$U\cdot X = Y$

$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}\cdot \begin{pmatrix}
x_1 \\ 
x_2 \\ 
x_3
\end{pmatrix} =  \begin{pmatrix}
1 \\ 
- \frac{23}{2} \\ 
\frac{52}{3}
\end{pmatrix}$

отсюда 

$x_3 = 1$

$x_2 = 0 $

$x_1 = - 1$


__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$



# Решение


$$ A = \begin{pmatrix}
81 & -45 & 45 \\ 
-45 & 50 & -15 \\ 
45 & -15 & 38
\end{pmatrix}$$


Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81} = 9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9} = -5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9} = 5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}= 5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 +25 \right )=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25 - 4}=3 $$

То есть:

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix},$$

$$L^T = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

отсюда 

$x_3 = -4$

$x_2 = -5 $

$x_1 = 6$


In [28]:
# chek
R = np.array([
              [9,0,0],
              [-5,5,0],
              [5,2,3]
            ])
matrA = R.dot(R.T)
matrA

array([[ 81, -45,  45],
       [-45,  50, -15],
       [ 45, -15,  38]])

In [29]:
x = np.array([
              [6],
              [-5],
              [-4]
])
matrA.dot(x)

array([[ 531],
       [-460],
       [ 193]])

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [30]:
def FLU (A):
  Lum = np.zeros_like(A)
  Uos = np.zeros_like(A)
  n = A.shape[0]
  for k in range(n):
    Lum[k, k] = 1
    Uos[k, k] = (A[k, k] - np.dot(Lum[k, :k], Uos[:k, k])) / Lum[k, k]
    for j in range(k+1, n):
      Uos[k, j] = (A[k, j] - np.dot(Lum[k, :k], Uos[:k, j])) / Lum[k, k]
    for i in range(k+1, n):
      Lum[i, k] = (A[i, k] - np.dot(Lum[i, :k], Uos[:k, k])) / Uos[k, k]
  return Lum, Uos

In [31]:
# chek
A = np.array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])
l,u = FLU(A)
print(l.dot(u))
print(l)
print(u)

[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]
[[1 0 0 0]
 [2 1 0 0]
 [3 5 1 0]
 [4 6 7 1]]
[[1 1 2 4]
 [0 3 4 1]
 [0 0 3 1]
 [0 0 0 4]]
